### ISSUE TITLE
[BUG] Chat stays in fixed position

### ISSUE THREAD

**Issue by roxandtol** [DarkKronicle/AdvancedChat#100]
**Describe the bug**
Chat stays in a fixed position after resizing window

**Minecraft Info**
Minecraft information: 1.17.1
- AdvancedChat-3.3.1-1.17-beta5

**To Reproduce**
1. Open a world in windowed mode
2. Open chat
3. Close chat
4. Change window size (or put it in fullscreen)
5. Open chat & see the error

**Expected behavior**
The chat to stay in a relative position instead of an absolute position

**Screenshots**
In windowed mode
![](https://i.imgur.com/FDCGJmG.png)
In Fullscreen mode
![](https://i.imgur.com/oN0bNAg.jpeg)
**Additional context**
Mod list
![](https://i.imgur.com/Fs1AaWl.png)

**Comment by DarkKronicle** [comment]
Archiving repository for modules https://github.com/DarkKronicle/AdvancedChatCore/wiki/Modules-List And this was implemented
