### ISSUE TITLE
Ability to set arbitrary RGB color of text in a replace filter

### ISSUE THREAD

**Issue by xanderstuff** [DarkKronicle/AdvancedChat#101]
**Is your feature request related to a problem? Please describe.**
Currently, the only way to set the color of text is to use minecraft's &# codes, with # being 0-F. 16 colors is a bit limiting.

**Describe the solution you'd like**
It would be nice to have a special color code for text that sets a the RGB value for the following text (and the color code gets taken out of the final text). Note: (just the starting `&`?) should be able to be escaped with `\` if someone for some reason wanted to literally write the color code.

Proposed format: `&[R,G,B]` where R, G, and B are 0-255
Proposed format: `&[RRGGBB]` where RRGGBB is a 6 digit hexcode for color

**Additional context**
requested by DarkKronicle on discord https://discord.com/channels/753693459369427044/792520837327880192/896878530858741820
![image](https://user-images.githubusercontent.com/68503800/136714526-30ce482a-ac2e-4768-b8c1-c5c3023ef3a8.png)
![image](https://user-images.githubusercontent.com/68503800/136714540-809416ff-b611-4269-91dd-9fd9f2286483.png)

**Comment by xanderstuff** [comment]
oh wait, I think this was supposed to go in this repo: https://github.com/DarkKronicle/AdvancedChatFilters

**Comment by xanderstuff** [comment]
@DarkKronicle I'll let you close this issue if this was indeed supposed to go in AdvancedChatFilters instead

**Comment by DarkKronicle** [comment]
👍
