### ISSUE TITLE
[BUG] Some issues with Chat log function

### ISSUE THREAD

**Issue by IJustWantANamePlease** [DarkKronicle/AdvancedChat#102]
**Describe the bug**
Chat log seems to have the same line limit as the chat HUD, instead of its own. Also, when limit is reached, it basically stops recording instead of replacing the old lines.

**Minecraft Info**
Minecraft information: 1.17.1 Fabric
- AdvancedChat version: AdvancedChat-3.3.1-1.17-beta5

**To Reproduce**
1. Set Chat HUD line limit to 100
2. Set Chat Log line limit to 1000
3. Spam
4. Chat Log should store 1000 messages, but it only has 100. According to the time stamp chat log stops recording new messages after limit is reached, while Chat HUD can still function.

**Comment by DarkKronicle** [comment]
This should be fixed with the AC Split. [Info](https://github.com/DarkKronicle/AdvancedChatCore/wiki/Modules-List)
