### ISSUE TITLE
Filter and tab management could be better

### ISSUE THREAD

**Issue by Madis0** [DarkKronicle/AdvancedChat#12]
I understand that you seem to be within your config API limits, but still... The overview, creation and deletion of filters and tabs are quite confusing. Maybe you can do some kind of split-screen view?

**Comment by DarkKronicle** [comment]
Yeah, I do agree that it isn't optimal. I hope to one day be able to create a better gui for filters and tabs, but currently I am just using [Cloth Config](https://github.com/shedaniel/cloth-config). Tried writing my own for v1, but it did not go well. I'll look into some options in the future.

**Comment by Toseflo** [comment]
Would also be great if there was a way to add multiple strings to a filter. For example I would like to get notified when my name appears in the chat. People write my name in many different ways and I would have to create a filter for each of those variations. With a filter-list I could simply add all those different Strings to one filter.

**Comment by DarkKronicle** [comment]
This is currently possible with a bit of use of Regular Expressions. Lets say I wanted to detect different ways that people say "DarkKronicle". This would be the regex:

`DarkKronicle|Darkk|Kron`

You use | to separate different strings to find. I know this isn't the easiest, but maybe eventually I'll add a way to have a list.

P.S. If you want ignorecase with the example above add `(?i)`. `(?i)DarkKronicle|(?i)Darkk|(?i)Kron`

**Comment by DarkKronicle** [comment]
Redoing it all for V3
