### ISSUE TITLE
Option to rename Main Chat Tab

### ISSUE THREAD

**Issue by Toseflo** [DarkKronicle/AdvancedChat#18]
I play on a server with multiple subservers and one of those is called "Mainserver". So I created a tab called "Main" for this server, but now it's a bit confusing with the default chat tab which is also called Main. Would be great if we could rename the default tab; I would probably rename it to "All" then.

**Comment by DarkKronicle** [comment]
I'll try to add this.

 Also, can you try to follow the built in templates (at least somewhat). Makes it a bit easier for me to help. Thanks!

**Comment by DarkKronicle** [comment]
This will be added next update.
