### ISSUE TITLE
[FEATURE] 1.15.2 Tab as seperatet chat

### ISSUE THREAD

**Issue by sphings79** [DarkKronicle/AdvancedChat#19]
Hi,

The tabs are really great, but it would be wonderful if it will be possible
to have the main chat on the bottom left an another tab e.g. the Private tab on bottom right.
So that it looks like the screenshot.
![Unbenannt](https://user-images.githubusercontent.com/43515272/88326018-eb192880-cd25-11ea-8fac-387d3dea77bd.PNG)

regards

sphings

**Comment by DarkKronicle** [comment]
I actually just had this idea a couple hours ago! I was thinking about how I could have some sort of way to replace banners. Will definitely try to add this soon.

**Comment by DarkKronicle** [comment]
Next update will have this!
