### ISSUE TITLE
Timestamp still shows even when entire message has been replaced with nothing.

### ISSUE THREAD

**Issue by jessiewestlake** [DarkKronicle/AdvancedChat#21]
When changing beds, minecraft sends a chat message saying you've "Respawn point set". I filtered that out and replaced it with nothing, but it still shows the timestamp with nothing after it. I would like to have the chat message completely gone as if it had never been received. It can show up in the logs, but not on my screen.

I am guessing I could probably filter it to a different chat tab, but I don't want a separate chat tab, I'd like to have it to where the message doesn't appear at all, including the timestamp.

I also want the timestamp to be there for non filtered messages.

![2020-07-23_22 07 21](https://user-images.githubusercontent.com/19229263/88355115-4e5c8800-cd31-11ea-93cb-a02113ad5bee.png)

**Comment by DarkKronicle** [comment]
Must have over looked this, shouldn't be too hard to fix. Thanks for the report.

**Comment by DarkKronicle** [comment]
Will be available soon for 2.0.5!
