### ISSUE TITLE
[BUG] Can't wake up when sleeping

### ISSUE THREAD

**Issue by Chronos22Gamer** [DarkKronicle/AdvancedChat#22]
**Describe the bug**
The nature of the Chat HUD screen means that you cannot wake up if you use a bed. Attempting to press escape also does not work. You can only wake up by disconnecting, or waiting for the night to pass. 

**Minecraft Info**
Minecraft information:
- AdvancedChat version: AdvancedChat-2.0.2-beta
- Minecraft Version: 1.15.2
- Fabric Version: 0.8.7 build 201
- Java Version: 64bit 1.8.0
- Using OpenGL v4.6 using the AMD Mesa Drivers

**To Reproduce**
1. Sleep in game
2. Attempt to wake up
3. Realize your narcoleptic fate

**Expected behavior**
There should be a "Leave Bed" button, or the escape key should wake the player up

**Screenshots**
n/a

**Additional context**
n/a

**Comment by DarkKronicle** [comment]
Thanks for using the template! Will add it to v2, and will hopefully get all these new features backported soon to v2-1.15.2. Will work soon.
