### ISSUE TITLE
[FEATURE] Chat HUD Configurable Location&Size

### ISSUE THREAD

**Issue by JVioleGrace** [DarkKronicle/AdvancedChat#23]
**Issue**
Confliction with other HUD mods.

**Hypothetical Solution**
Configurable location of chat HUD, preferably drag n' drop.

**Reference for the HUD confliction**
![Screen Shot 2020-07-27 at 1 34 46 AM](https://user-images.githubusercontent.com/65801648/88513319-b15a5300-cfad-11ea-9972-988e7ee37822.png)
Confliction with mod, RPG HUD. I have contacted the author of RPG HUD, and confirmed that the confliction is due to AdvancedChat overriding RPG HUD's chat HUD location and size.

**Comment by DarkKronicle** [comment]
This should already be implemented. In the Config screen under the category *Chat Config* there is a dropdown labled "Chat HUD Position Settings". If this still doesn't show up could you let me know what version you are using?
