### ISSUE TITLE
[FEATURE]Chat HUD/Tab Design

### ISSUE THREAD

**Issue by JVioleGrace** [DarkKronicle/AdvancedChat#24]
**Chat HUD Design Suggestion**
1. Ability to toggle the option of displaying several(1-3) chats (tabs) simultaneously.
2. View chat tabs similar to that of a web browser.

**Reference Images**
1. Simultaneous Display
![Screen Shot 2020-07-27 at 2 18 42 AM](https://user-images.githubusercontent.com/65801648/88514482-cb953080-cfaf-11ea-8db0-85c035676f06.png)

2. Browser Chat Tabs
![Screen Shot 2020-07-27 at 2 17 28 AM](https://user-images.githubusercontent.com/65801648/88514515-dd76d380-cfaf-11ea-8f72-ca251310a2f6.png)

**Additional Notes**
I suggest allowing the chat to be interactive, allowing the user to click both on the chat itself and the chat tabs, maximizing the smoothness and usability of this mod.

**Comment by DarkKronicle** [comment]
Thanks for using the template :D

I am planning to add the ability to view different chat tabs at the same time in the near future. Currently I am working on an GUI API to give me the ability to make configuring and overall appearance of AdvancedChat better. Could you elaborate on what you mean by having the user be able to click on the chat and tabs?

P.S. Here's a little sneak peek at the GUI. (All of them use nice animations)
![image](https://user-images.githubusercontent.com/38167691/88591806-28c5cc00-d01a-11ea-9184-c910ddaaf245.png)

**Comment by JVioleGrace** [comment]
I'm thinking of how applications on a computer can be displayed simultaneously when only one of them is selected. You can chat in each "application" or chat by selecting it, either by clicking the chat logs, or the chat tabs.

**Reference Images**
![Screen Shot 2020-07-28 at 9 07 54 AM](https://user-images.githubusercontent.com/65801648/88676629-ed76dc00-d0b1-11ea-81ca-fe0822ebe8dd.png)                ![Screen Shot 2020-07-28 at 9 07 54 AM](https://user-images.githubusercontent.com/65801648/88676629-ed76dc00-d0b1-11ea-81ca-fe0822ebe8dd.png)
![Screen Shot 2020-07-28 at 9 08 28 AM](https://user-images.githubusercontent.com/65801648/88676632-ef409f80-d0b1-11ea-8934-9946e67a09b7.png)    ![Screen Shot 2020-07-28 at 9 08 28 AM](https://user-images.githubusercontent.com/65801648/88676632-ef409f80-d0b1-11ea-8934-9946e67a09b7.png)

You could possibly display selection by highlighting one of the chats.

**Comment by DarkKronicle** [comment]
Next update will have support for having multiple chat windows open!
