### ISSUE TITLE
1.16.2 Support

### ISSUE THREAD

**Issue by Boobies** [DarkKronicle/AdvancedChat#26]
Unfortunately, the 1.16.1 version crashes the game. Could we expect an update soon?

**Comment by DarkKronicle** [comment]
I've started work on it, but it seems to be another somewhat complex update. Mojang decided that them redoing most of text handling for the 1.16 update was not enough, so they redid a lot of it again for 1.16.2.

**Comment by AppDevMichael** [comment]
Any updates on this?

**Comment by Boobies** [comment]
If you plan on looking into 1.17, make sure it works as expected with the social feature, where you can mute players.
