### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DanShu15** [DarkKronicle/AdvancedChat#3]
Potentially outside of the scope of your mod, but there was an awesome feature in RAD for 1.12 Forge where you could mouse over an item and Shift+T to display that item with it's enchants and information in the chat.

Would that be possible with AC?

**Comment by DarkKronicle** [comment]
Sorry I took so long to respond! I'm working on the 1.16 update right now and part of what I want to do is rewrite a lot of the logic inside of the code. If I get this working I will try to add the enchants. I'll let you know if any progress is being made on the enchantments.

**Comment by DanShu15** [comment]
Actually the Linkissimo mod does what I was talking about, altho atm it's not hotkey rebindable. Updating my modpack to 1.16 as things come available myself tho, so I'll keep an eye on advanced chat for sure 🙂

**Comment by DarkKronicle** [comment]
Update to 1.16 is almost done, so I'm looking at the Linkissimo mod and was wondering if I got what feature you wanted correctly. Basically if you hit a keybind while hovering over an item in your inventory, it will put that item information into the chat. Could you tell me what format the message is and how you would like it?

**Comment by DanShu15** [comment]
Yep, so shift+t or whatever hotkey with your mouse over an item puts the item info into your chat to share.
If you have a diamond sword named Tom and linked it in chat it'd show up as a colored Tom, then depending on your mods installed you could shift+mouse over, just mouse over, or click it to see the items stats and enchants

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DarkKronicle** [comment]
Looked into this a bit, seems like a bit of work to get this into AdvancedChat and I don't really think that it fits it entirely. This feature may get added later, but for now I'm going to close this issue.
