### ISSUE TITLE
Publish AdvancedChat on Modrinth

### ISSUE THREAD

**Issue by Toseflo** [DarkKronicle/AdvancedChat#32]
Since the update of AdvancedChat should be pretty close, I would suggest also publishing the newest version of the mod on modrinth.com. Modrinth is the new up and coming mod hosting site, which promises giving as much money as possible to publishers. So it's probably also in your interest to publish mods on Modrinth ;)

**Comment by DarkKronicle** [comment]
I'll take a look into that. Thanks :)
