### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CWallace89** [DarkKronicle/AdvancedChat#33]
**Describe the bug**
Only one highlight filter can be active at any one time. Once I create a new filter that includes a text highlight, the previous filter that was highlighting text stops working (the filter still detects as it plays sound, it just doesn't highlight the line any more).

**Minecraft Info**
Minecraft information:
- AdvancedChat 2.1.0, Minecraft Java 1.16.5

**To Reproduce**
1. Create a filter including a text highlight
2. Test, filter should work
3. Create a new filter including a text highlight
4. Test, filter should work
5. Test the first filter you made, highlight will no longer work

**Expected behavior**
I expected to be able to have multiple filters working at once to highlight different categories.

**Comment by DarkKronicle** [comment]
Just fixed in (2.1.1 hopefully it is approved on curseforge by now)
