### ISSUE TITLE
[FEATURE] Vanilla Like Chat

### ISSUE THREAD

**Issue by barraIhsan** [DarkKronicle/AdvancedChat#34]
So, my problem is the background chat is not like the vanilla (there is maybe an option to set it), and the button background (setting, chat log) is so small, I suggest adding some padding into the button

And the last one, please add an option to hide the chat tabs switch button on the right side of the chat
![image](https://user-images.githubusercontent.com/57800056/108143576-9a6e8000-70fa-11eb-9fec-2c393216f08d.png)
yes I know you can adjust the letter, but there is no option for 0 letter

**Comment by DarkKronicle** [comment]
You can change the background color in settings. If you're talking about it taking up the full height at all times that is there for the chat tabs and easier vision. 

In the next update (2.1.1 Hopefully it's on curseforge by now) you can disable the chat tab list.
