### ISSUE TITLE
[BUG] Changing chat width doesnt update

### ISSUE THREAD

**Issue by barraIhsan** [DarkKronicle/AdvancedChat#35]
**Describe the bug**
When you change the width of the chat, the chat is still not wide (that's mean, only the background wider)

**Minecraft Info**
Minecraft information:
- AdvancedChat version 2.1.0

**To Reproduce**
1. Go to Settings
2. Click on Chat Config
3. Scroll down to Chat HUD Width
4. Change the width maybe 350
5. Click Save & Quit
6. Type ---------------------------------------------------------
7. See error

**Expected behavior**
The chat should also get wider (not just the background)

**Screenshots**
![image](https://user-images.githubusercontent.com/57800056/108146702-3c449b80-7100-11eb-9a76-00de9d4d56b3.png)

**Additional context**
My mod list :
![image](https://user-images.githubusercontent.com/57800056/108146721-45ce0380-7100-11eb-932a-cdadf362971c.png)

**Comment by DarkKronicle** [comment]
This should be fixed next update

**Comment by DarkKronicle** [comment]
It's fixed on AdvancedChat 2.1.1. (hopefully it's approved on curseforge)
