### ISSUE TITLE
[FEATURE] Chat log to file

### ISSUE THREAD

**Issue by IZeeXeS** [DarkKronicle/AdvancedChat#37]
please add to mod ability to write the chat log to a file

**Comment by Boobies** [comment]
Upvote.

**Comment by DarkKronicle** [comment]
Minecraft by default already exports your chat logs. Do you mean exporting search results?

**Comment by K0-RR** [comment]
> Minecraft by default already exports your chat logs.

Whoa what where? You mean in the game log? But there is anything else too. I think the author wanted something to save every message to E.g. /chatlog/hypixel/10-03-2021.txt (client side so only when he was online). Basically like #50 but I wanted it to be like you join a server and you can scroll in-game chat to see messages from previous days. (Yes client side)

**Comment by Boobies** [comment]
At the very least, it would be nice to be able to view the chat logs in-game rather than having to manually decompress general-purpose logs and then apply regular expressions on the text to extract the relevant information from them.

**Comment by CyberFoxar** [comment]
A feature to log a specific tab/set of message would be immensly useful, and quite better than filtering manually minecraft's logs.

Bonus points if formatting is kept. There used to be a similar plugin that made HTML files which kept close to the original formatting and was quite human-readable, as well as machine-readable.

**Comment by DarkKronicle** [comment]
Archiving for modules https://github.com/DarkKronicle/AdvancedChatCore/wiki/Modules-List This may be added to log
