### ISSUE TITLE
Crash on opening settings.

### ISSUE THREAD

**Issue by Nutterr** [DarkKronicle/AdvancedChat#38]
When I open the settings menu the game instantly closes and gives me this error.

The game crashed whilst mouseclicked event handler
Error: java.lang.NoClassDefFoundError: io/github/prospector/modmenu/api/ModMenuApi
Exit Code: -1

**Comment by DarkKronicle** [comment]
Do you have mod menu installed? if so, can you send me a list of your mods.

**Comment by jnkyto** [comment]
I have the exact same issue. I tried with only the fabric API and this mod, still no luck. Immediately after clicking the 'Settings' button in the chat screen, Minecraft freezes and crashes after a few seconds. Attached is a crash dump file.
[crash-2021-02-27_14.44.23-client.txt](https://github.com/DarkKronicle/AdvancedChat/files/6054433/crash-2021-02-27_14.44.23-client.txt)

EDIT: To clarify, this is using 2.1.1, the most recent version uploaded to CurseForge.

**Comment by madc24** [comment]
I have the same problem;
these are the mods i have installed https://prnt.sc/108m1vm

**Comment by DarkKronicle** [comment]
The way the configuration screen's work it is required to have ModMenu. Let me know if it works.

https://www.curseforge.com/minecraft/mc-mods/modmenu

**Comment by jnkyto** [comment]
Unfortunately, it now gives an another error. My mods are now AdvancedChat-2.1.1.jar, fabric-api-0.31.0+1.16.jar and modmenu-1.16.8.jar.

[crash-2021-02-27_21.40.19-client.txt](https://github.com/DarkKronicle/AdvancedChat/files/6055249/crash-2021-02-27_21.40.19-client.txt)

EDIT: The Settings-button works after downloading Cloth Config API https://www.curseforge.com/minecraft/mc-mods/cloth-config/

**Comment by kyleremp** [comment]
@jnkyto regarding this:

EDIT: The Settings-button works after downloading Cloth Config API https://www.curseforge.com/minecraft/mc-mods/cloth-config/

Thank you so much, I was experiencing the same issues and couldn't find a solution, installing this finally resolved it.

**Comment by DarkKronicle** [comment]
This shouldn't happen anymore in v3, so I'm going to close this. Feel free to open another one if this continues to happen.
