### ISSUE TITLE
Removing all chat tabs results in a crash

### ISSUE THREAD

**Issue by Chronos22Gamer** [DarkKronicle/AdvancedChat#4]
Title explains it all. Tried to delete the "default" tab that comes with a fresh install, as it's made redundant by the "main" tab, but instead resulted in a crash.  

Attached is two crash reports caused by this issue, one trying to delete the "Default" tab, and one where I create a second tab, remove the "default" tab, and then try to delete the new tab. 

[crash-2020-07-20_16.30.47-client.txt](https://github.com/DarkKronicle/AdvancedChat/files/4949951/crash-2020-07-20_16.30.47-client.txt)
[crash-2020-07-20_16.34.38-client.txt](https://github.com/DarkKronicle/AdvancedChat/files/4949952/crash-2020-07-20_16.34.38-client.txt)

**Comment by DarkKronicle** [comment]
Has been fixed in the code, will soon be added to the release. Gonna mark this as closed. Thanks for your contribution!
