### ISSUE TITLE
[FEATURE] Filter messages to a different chat tab

### ISSUE THREAD

**Issue by MrRubberDucky** [DarkKronicle/AdvancedChat#40]
**Is your feature request related to a problem? Please describe.**
Nope, it's not.

**Describe the solution you'd like**
Ability to use message filters to filter certain messages into different chat tabs without them being shown in the main tab.
Ex. Instead of replace message, add another option titled "Move to different chat tab", so for example if the chat filter has "WTS" filter set on it and if someone sends "WTS > Diamond Block for 10 Emeralds", the message doesn't get shown in the General tab and instead would get shown in Trading tab.

**Additional context**
Being able to seperate messages based on filters to different tab channels would reduce clutter and provide better solution for those that want to for example seperate whispers, trading and combat messages from different mods or vanilla itself.

**Comment by MrRubberDucky** [comment]
nvm I noticed i can do that from chat tabs lmao, but would be good to have this option also in chat filters

**Comment by DarkKronicle** [comment]
Thanks for following the template! For now I don't see a lot of use to also have filters point to chat tabs. It would be useful to easily have multiple filters line in. Maybe I'll add those to chat tabs later.

Glad you found what you were looking for!
