### ISSUE TITLE
Crash involving Tech Reborn [BUG]

### ISSUE THREAD

**Issue by GekidoLukas** [DarkKronicle/AdvancedChat#41]
**Describe the bug**
The Game Crashes when you right-click items that send/change messages in chat. (Industrial items that change modes)

**Minecraft Info**
Minecraft information:
- AdvancedChat-2.1.1
- TechReborn-1.16-3.8.1+build.211.jar
- Fabric : fabric-loader-0.11.2-1.16.5

**To Reproduce**
1. Download both mods and use the fabric version as well.
2. Start the game and get an industrial item (eg. techreborn:industrial_drill)
3. Sneak+Right-click the item

**Expected behavior**
Observe the game crashing.

**Screenshots**
Items to reproduce the crash:
![industrial items](https://user-images.githubusercontent.com/59490449/109427923-e7a0fa80-79f4-11eb-9e23-2c6b94783de9.png)

**Additional context**
https://www.curseforge.com/minecraft/mc-mods/techreborn

**Comment by James103** [comment]
Do you have the crash report? If so, can you please post it here?

**Comment by DarkKronicle** [comment]
If you do happen to find the crash report I may take a look at it. Going to close this for being inactive.
