### ISSUE TITLE
[FEATURE] Add padding?

### ISSUE THREAD

**Issue by barraIhsan** [DarkKronicle/AdvancedChat#42]
So i want the chat have the padding. Sometimes people just add a little bit of space between the screen and chat (see the picture to understand)
![image](https://user-images.githubusercontent.com/57800056/109661784-edd1db00-7b9c-11eb-9d41-270f695ab24c.png)
But the problem the background thing, doesn't extend. So there is some space, and also don't look a little bit ugly

(Sorry for bad English lol)

**Comment by DarkKronicle** [comment]
Added in v3.0.5! Should be on curseforge soon!
