### ISSUE TITLE
[BUG] MacOS Retina display breaks hover and links

### ISSUE THREAD

**Issue by magicus** [DarkKronicle/AdvancedChat#43]
**Describe the bug**
Links in the chat -- both URL:s and command links do not work when AdvancedChat is installed.

**Minecraft Info**
Minecraft information:
- AdvancedChat version 2.1.1

**To Reproduce**
1. Send a URL in chat, e.g. `http://www.google.com/`
2. Try to click on link, nothing happens.

**Expected behavior**
The vanilla experience ("Do you want to follow this link?" dialog appearing)

**Screenshots**

**Additional context**
The same goes for chat messages that include links which expand to command. I'm not sure how to craft those as a user, but when the server sends them out, it does not work.

This bug severely reduces the usability of AdvancedChat. :-( Since text cannot be copied, and URLs cannot be clicked, it basically makes it impossible to use AdvancedChat if you want to have the ability to follow a URL.

**Comment by DarkKronicle** [comment]
Hmm, does chat hovering work for you as well? (Easy way to test is to /give yourself any item and hover over what you got in chat). If that does work there's probably some weird Minecraft behavior that I can look into.

**Comment by magicus** [comment]
At first I thought chat hovering did not work either. Then I realized that it did work, sort of. But it is offset from the actual text. An educated guess is that this is a Retina problem. (I'm using a mac with retina display, and a lot of minecraft mods has run into issues due to this.) It looks like the hover location is based on a cursor position that is a factor larger than the actual text. I'll provide a screenshot. You cannot see the cursor in it, but the hover box is right above it.

**Comment by magicus** [comment]
I could have sworn that you were able to attach files to Github issues... Can't find it now. Anyway, imgur to the rescue:
https://imgur.com/a/07I5eVy

**Comment by DarkKronicle** [comment]
Seems I found the problem (it's not your display :D). Just to double check that I am thinking of the right thing, is your chat scale not at 100%?

**Comment by DarkKronicle** [comment]
Ok, the update is now posted to curse forge! (2.1.2) and modrinth soon. Let me know if that doesn't work.

**Comment by magicus** [comment]
You are indeed correct, I had the scale at 50%.

And 2.1.2 solves the problem! Thank you so much for the speedy resolution!
