### ISSUE TITLE
[BUG] Unable to change color of triggered filters 

### ISSUE THREAD

**Issue by Open24Hours** [DarkKronicle/AdvancedChat#44]
As of now the only way to change the color is to also replace the text. But in my case, I am attempting to change the color of users names at the start of lines as well as remove the chevrons. right now I am using regex ^<.+?> to match. i just want to change the color of the match, not alter the text. I can't simply put the phrase in the replace to box because it has a variable in it, each players unique username.

**Comment by DarkKronicle** [comment]
Implemented this feature in the next update (2.1.3) (should be uploaded soon). You will now have the option to put %MATCH% in toReplace and when it replaces the text, it will replace %MATCH% with whatever was matched.

**Comment by DarkKronicle** [comment]
It may actually be a bit longer because I'm planning a much bigger release, but if you want to test out the beta versions you can join the [discord](https://discord.gg/WnaE3uZxDA)

**Comment by DarkKronicle** [comment]
Will be on v3
