### ISSUE TITLE
[BUG] The images on the mod's Curseforge page return HTTP 404 on load.

### ISSUE THREAD

**Issue by James103** [DarkKronicle/AdvancedChat#46]
**Describe the bug**
The following URLs listed in the [project README](https://github.com/DarkKronicle/AdvancedChat) and on the [Curseforge page](https://www.curseforge.com/minecraft/mc-mods/advancedchat) all return 404 errors, causing the images to not load:
```
https://raw.githubusercontent.com/DarkKronicle/AdvancedChat/v2/images/alternate.png
https://raw.githubusercontent.com/DarkKronicle/AdvancedChat/v2/images/colors.png
https://raw.githubusercontent.com/DarkKronicle/AdvancedChat/v2/images/logscreen.png
https://raw.githubusercontent.com/DarkKronicle/AdvancedChat/v2/images/tab.png
```

**Minecraft Info**
Minecraft information:
- AdvancedChat version 917a946dba8e7ff24bb418c09efcd05ac0d8d781

**To Reproduce**
1. Check the images on the [Curseforge page](https://www.curseforge.com/minecraft/mc-mods/advancedchat).
2. Check the images in the [project README](https://github.com/DarkKronicle/AdvancedChat).
3. Using Github's file finder on the default branch of `v2`, search for the file extension `.png`.
4. Only a single result is returned, which corresponds to the project's icon.

**Expected behavior**
1. The images on the Curseforge page load successfully.
2. The images in the project README load successfully.
3. Using Github's file finder, at least 5 results are returned, with the missing images added in.

**Screenshots**
From the Curseforge page:
![image](https://user-images.githubusercontent.com/37945304/110542318-83fe8780-80ee-11eb-89e8-86f3afd797f6.png)

From the project README with GitHub's dark mode:
![image](https://user-images.githubusercontent.com/37945304/110542381-95e02a80-80ee-11eb-81b8-69f25c8223f4.png)

From opening up each of the images in a new tab and checking the result:
![image](https://user-images.githubusercontent.com/37945304/110542478-b4debc80-80ee-11eb-9ad1-45f99aec9296.png)
(in all 4 cases)

**Comment by DarkKronicle** [comment]
Should be there now!
