### ISSUE TITLE
[BUG] crash instantly after trying to open chat

### ISSUE THREAD

**Issue by shouxd** [DarkKronicle/AdvancedChat#47]
https://paste.gg/p/anonymous/4f1e33ff807c44ad820d8f10b1979ff1

Chat doesnt even appear before game crashes

**Comment by DarkKronicle** [comment]
I'm going to close this as inactive and I'm pretty sure v3 fixes this. Let me know if it doesn't.

**Comment by hackaholic5069** [comment]
i experienced this bug recently @DarkKronicle 
[crash-2021-08-01_23.35.14-client.txt](https://github.com/DarkKronicle/AdvancedChat/files/6914849/crash-2021-08-01_23.35.14-client.txt)
