### ISSUE TITLE
[FEATURE] Option for nested Regex Replacing

### ISSUE THREAD

**Issue by K0-RR** [DarkKronicle/AdvancedChat#49]
An option to remove the brackets like here:
![image](https://user-images.githubusercontent.com/43277609/110607433-7b0fc380-818b-11eb-9e0e-2ebd258a7255.png)

**Comment by Chronos22Gamer** [comment]
You can accomplish this by using resourcepacks, changing `en_us.json` specifically
Here's a quick resourcepack I whipped up to demonstrate this

[NoChatBrackets.zip](https://github.com/DarkKronicle/AdvancedChat/files/6118972/NoChatBrackets.zip)

**Comment by DarkKronicle** [comment]
Gonna work on having nested filters for easy control of stuff that can do this.

**Comment by K0-RR** [comment]
@Chronos22Gamer It's working thx.

**Comment by DarkKronicle** [comment]
Resource pack works and for v3 there will be an option to make a filter to do this.
