### ISSUE TITLE
Banner position request

### ISSUE THREAD

**Issue by sphings79** [DarkKronicle/AdvancedChat#5]
Hi,

I'm using advancedchat-0.1.1.jar for 1.15.2 and I'm missing a future where i can select where to show the banner.
Would be nice to get an option to select top left, top right, bottom right.

regards

sphings

**Comment by DarkKronicle** [comment]
Thanks for all the feedback! I coded a full rewrite for 1.16 that has a lot more features and just works better in general. I am thinking to maybe try to back port it and re-add the banner feature. I will add that feature when I get around to the banners.

**Comment by DarkKronicle** [comment]
Support for v1 has now been ended recently ended. There are plans to add a similar banner like feature in the future. Sorry that it isn't added right now, but stay tuned!
