### ISSUE TITLE
[FEATURE] Chat history.

### ISSUE THREAD

**Issue by K0-RR** [DarkKronicle/AdvancedChat#50]
Slightly related to https://github.com/DarkKronicle/AdvancedChat/issues/37
A feature like here (this mod doesn't work with 1.16.5) https://www.curseforge.com/minecraft/mc-mods/chat-history

**Comment by DarkKronicle** [comment]
That is a serverside mod, so I don't plan on adding those features (since AdvancedChat is client side). If someone else wants to make it, feel free to submit a PR!
