### ISSUE TITLE
[BUG] Game crashes when opening chat if you have the tweakChatPersistentText feature from tweakeroo active.

### ISSUE THREAD

**Issue by Joulanh** [DarkKronicle/AdvancedChat#55]
**Describe the bug**
Game crashes when opening chat if you have the tweakChatPersistentText feature from tweakeroo active.
It would allow you to retain text you havent send yet if you leave the chat box.

**Minecraft Info**
Minecraft information:
-Minecraft 1.16.5
-AdvancedChat 2.1.2 
-tweakeroo-fabric-1.16.4-0.10.0
-malilib-fabric-1.16.4-0.10.0
-mod-manager

**To Reproduce**
1. go into the tweakeroo confic and set the tweakChatPersistentText tweak under toggle tweaks to true 
2. open chat

**Comment by DarkKronicle** [comment]
I'll add this to version 3!

**Comment by DarkKronicle** [comment]
Added in v3!
