### ISSUE TITLE
Clear chat messages on Disconnect doesnt work in chat logs

### ISSUE THREAD

**Issue by barraIhsan** [DarkKronicle/AdvancedChat#56]
**Describe the bug**
So when we set the `Clear chat messages on Disconnect doesnt work in chat logs` to `Yes`, then it will clear the chat, BUT it DOESNT clear chat in chat log

**Minecraft Info**
Minecraft information:
- AdvancedChat-2.1.1

**To Reproduce**
1. Go to the mod config (Via ModMenu, or open chat and click `Settings`)
2. Turn on `Clear chat messages on Disconnect doesnt work in chat logs`
3. Type `test` in chat
4. Save and Quit / Disconnect
5. Join again

**Expected behavior**
The chat logs also cleared. Or maybe there is new button for clear chat log

**Comment by DarkKronicle** [comment]
Fixed in new beta
