### ISSUE TITLE
[BUG] Leave Bed

### ISSUE THREAD

**Issue by barraIhsan** [DarkKronicle/AdvancedChat#57]
**Describe the bug**
When you sleep on the bed, and its day (because of sleep). We kicked out of a bed (that is normal), But the chat is still open and there is still the `Leave Bed` button

**Minecraft Info**
Minecraft information:
- AdvancedChat-2.1.1

**To Reproduce**
1. Set the time to night (`time set night`)
2. Sleep in the bed
3. Wait until its morning
4. See Bugs

**Expected behavior**
In vanilla, if you kicked out of a bed the text chat is closed

**Comment by DarkKronicle** [comment]
Hmm, I remember fixing this at one point while developing. It may have been fixed in AdvancedChat-2.1.2, if that doesn't work you can try the beta on my discord that should have it fixed. https://discord.gg/WnaE3uZxDA

**Comment by barraIhsan** [comment]
Also maybe there is a notification if there is an update? For example use [ModUpdater](https://www.curseforge.com/minecraft/mc-mods/modupdater)

**Comment by barraIhsan** [comment]
Ok it already fixed at new version
