### ISSUE TITLE
[BUG] "ChatCalc" mod compatibility.

### ISSUE THREAD

**Issue by HappyClownn** [DarkKronicle/AdvancedChat#59]
I was using a mod called "ChatCalc". Its basicly allows you to perfrom some calculations ingame, without using a calculator app. But, it doesn't work with your mod.

The problem is, when I wrote 2+2, i need to press "TAB" to see the results. With your mod, when I press tab, nothing happens.

Mod link: [https://www.curseforge.com/minecraft/mc-mods/chatcalc](url)

The version of your mod: AdvancedChat-3.0.4-1.16.5

Thanks in advance.

**Comment by DarkKronicle** [comment]
Too bad that mod isn't open source! I'm planning on adding a custom command completer (I guess message completer now?) that people can interface into. If I get that working this should be not too hard. I'll look into it.

**Comment by HappyClownn** [comment]
I'm not very good at programming, but it would be great if you could bring an option to your mod to make in-game calculations. Also thanks for your quick response!

**Comment by K0-RR** [comment]
I created a Feature Request for easier tracking and historical purposes. #60

**Comment by DarkKronicle** [comment]
Will be added in next update (time tbd)
