### ISSUE TITLE
[FEATURE] Item linking.

### ISSUE THREAD

**Issue by K0-RR** [DarkKronicle/AdvancedChat#61]
An option to show my item in the chat.

To link an item, simply type in your message [item] while holding it
![image](https://user-images.githubusercontent.com/43277609/113352834-1afcdf00-933d-11eb-8f20-efb4020c7776.png)

**Comment by DarkKronicle** [comment]
I would only be able to put the name on it or have only you to be see it. Only the server can send the special text that includes item information.

**Comment by K0-RR** [comment]
I suppose you are not interested in making small addon-like mod for servers (AdvancedChat server compatibility mod) just to make features like this possible?

**Comment by DarkKronicle** [comment]
Archived for modules https://github.com/DarkKronicle/AdvancedChatCore/wiki/Modules-List
