### ISSUE TITLE
[BUG] Text is going out of the text box

### ISSUE THREAD

**Issue by K0-RR** [DarkKronicle/AdvancedChat#64]
![image](https://user-images.githubusercontent.com/43277609/114282769-4fac1d00-9a46-11eb-96ec-cd346d4ea2cb.png)

**Comment by DarkKronicle** [comment]
A temporary fix may be to increase right chat pad

**Comment by K0-RR** [comment]
20 (seems to be max) seems good. Thx. This seems to happen because of the Chat Heads feature.

**Comment by DarkKronicle** [comment]
Ok. Thanks for letting me know that Chat heads caused it :)

**Comment by DarkKronicle** [comment]
Should be fixed next version :)
