### ISSUE TITLE
[BUG] Chat heads aren't fading out with the rest of the chat (text).

### ISSUE THREAD

**Issue by K0-RR** [DarkKronicle/AdvancedChat#67]
AdvancedChat version - 3.0.5
![image](https://user-images.githubusercontent.com/43277609/114453753-1e645600-9bda-11eb-86a8-b7bc578add7e.png)

**Comment by DarkKronicle** [comment]
It's a weird bug I don't really know how to fix. I'm setting transparency to be the proper amount, but they're not fading out. I'll take a look again.

**Comment by maxsupermanhd** [comment]
Confirmed, 3.2.0
![image](https://user-images.githubusercontent.com/20772987/128969130-28ed17f3-5be5-4001-b70b-a2f4ea584f4b.png)

**Comment by DarkKronicle** [comment]
https://github.com/DarkKronicle/AdvancedChatCore/wiki/Modules-List Archived for modules. Will try to take a look at this with better knowledge on rendering.
