### ISSUE TITLE
[BUG] Filters have 128 character limit in String to Find

### ISSUE THREAD

**Issue by Toseflo** [DarkKronicle/AdvancedChat#68]
**Describe the bug**
In version 2.x.x of AdvancedChat, you were able to have an unlimited (?) amount of characters in the "String to Find"-field of your chat filter.  In versions 3.1.0 and probably some versions before, this is reduced to 128 characters. I have a RegEx filter, which needs 150 characters to function. And this filter is now broken in the newest version of AdvancedChat.

**Minecraft Info**
Minecraft information:
- AdvancedChat-3.1.0-1.16.5.jar
- 
**Expected behavior**
There shouldn't be a such a small character limit for String to Find.

**Comment by DarkKronicle** [comment]
Will be fixed next update :)

**Comment by Toseflo** [comment]
Sadly the bug still isn't fixxed. When you close the filter configurator and open it again, the String to Find is again reduced to 128 characters and the other characters are deleted.
Also in Chat Tabs, there still is the hard 128 character limit. Would be great if you could also increase the limit there.
