### ISSUE TITLE
[Feature] Spell checker for other languages

### ISSUE THREAD

**Issue by Toseflo** [DarkKronicle/AdvancedChat#69]
Is there some way how the players can change the language of the spell checker? There isn't much information to spell checkers in the info page and I haven't found a way to change the language myself. 
Would be great if you could add some information how to add more languages yourself or if you could add the most prominent languages per default. This list (https://minecraft-statistic.net/en/global_statistic.html) suggests that German, Russian, Ukrainian and France would be the most spoken languages by Minecraft players, so they would be most helpful to add.

**Comment by Toseflo** [comment]
I wasn't able to re-open issue #68, so I just leave this message here so that you don't overlook my comment in #68. It isn't related to this issue at all, but I thought it's easier to notice than a comment on a closed issue.

**Comment by DarkKronicle** [comment]
I'll look into adding other languages for the spell checker. Most spell checkers are super old for java so I need to modify the one I'm using to make it easier to add more. Temporarily, you can replace english.zip in ./config/AdvancedChat with the jar files found in any of these directories (http://www.softcorporation.com/products/spellcheck/dictionaries/). Make sure the rename the jar to english.zip. 

I will also look into #68 again. 

Thanks!

**Comment by DarkKronicle** [comment]
Archiving for modules https://github.com/DarkKronicle/AdvancedChatCore/wiki/Modules-List This may make it's way into box
