### ISSUE TITLE
Selectable sound

### ISSUE THREAD

**Issue by sphings79** [DarkKronicle/AdvancedChat#7]
Hi,

it would be fine, if we had the option to change the notification sound.
If it's not possible to change the sound within the mod, is it a system sound so we can replace the system file?

regards

sphings

**Comment by DarkKronicle** [comment]
Sounds like an awesome feature. I'll try to figure out a way to make that possible.

**Comment by DarkKronicle** [comment]
Added. Will be available soon for 1.15 (hopefully)
