### ISSUE TITLE
[Feature] Delete button should have a cooldown

### ISSUE THREAD

**Issue by Toseflo** [DarkKronicle/AdvancedChat#70]
**Is your feature request related to a problem? Please describe.**
It's way too easy to accidentally delete a chat tab or chat filter. And considering that some players probably spend a good amount of time on configuring the filters, it would be a shame if the whole filter would be gone with one missclick.

**Describe the solution you'd like**
I have seen some mods have some kind of cooldown with a loading bar on their delete button so that you have to press delete for 3 seconds before the button works. Or a confirmation screen whether you really want to delete the filter would be helpful. Or simply increasing the distance between the configure and delete button could already.

**Comment by DarkKronicle** [comment]
I'll see if this could be implemented easily. If you do happen to accidentally remove a filter that you didn't mean to, as long as you don't leave the world/close the game, the config file itself (`./config/advancedchat/advancedchat.json`) won't actually be updated, so you can copy that.

**Comment by DarkKronicle** [comment]
Archiving for modules https://github.com/DarkKronicle/AdvancedChatCore/wiki/Modules-List With a GUI update this may be implemented
