### ISSUE TITLE
[BUG] Children filters may not work

### ISSUE THREAD

**Issue by StarsDown64** [DarkKronicle/AdvancedChat#71]
**Describe the bug**
Child filters will not execute. 
Normal layer 0 filters will correctly execute their filter but any filter settings stored in a child will not work.

**Minecraft Info**
Minecraft information:
- AdvancedChat 3.2.0
- Minecraft 1.16.5
- Fabric 0.11.3
- Fabric API 0.33.0
- Malilib 0.10.0-dev.21+arne.5

**To Reproduce**
1. Create a new filter example:
2. String to find Literal "alpha"
3. Replace to Children
4. Create a new child filter example:
5. String to find Literal "alpha"
6. Replace to Only Match "beta"
7. Activate both parent and child filter
8. Type "alpha" in chat

**Expected behavior**
The word "alpha" is replaced with "beta"
(The word is not replaced in game)

**Screenshots**
![image](https://user-images.githubusercontent.com/19573997/116186164-14217c00-a6f1-11eb-8f56-57997f0a4c64.png)
![image](https://user-images.githubusercontent.com/19573997/116186178-1a175d00-a6f1-11eb-8ddd-40893a044ce7.png)
![image](https://user-images.githubusercontent.com/19573997/116186219-2e5b5a00-a6f1-11eb-8ae3-f3b31f4dbc65.png)

**Additional context**
This is just a most basic example, it applies to all filter options like colors, sounds, etc. They just don't work from child filters.
This used to work as of v3.0.5 (not sure of 3.1.0, skipped that version)
If you want to do some real-time work DM me and I'll send you my Discord.

**Comment by DarkKronicle** [comment]
I'll look into this again. Thanks!

**Comment by DarkKronicle** [comment]
I think this is fixed in the AdvancedChat split, I can't seem to reproduce it. If this still happens I can send you some beta jars.
