### ISSUE TITLE
[BUG] Chat tabs are displayed in two locations and one of them is cropped.

### ISSUE THREAD

**Issue by K0-RR** [DarkKronicle/AdvancedChat#73]
AdvancedChat version 3.2.0.
Why is there a "Main" and "Mai" button and also why we have two buttons to do the same thing? I only tested the mod in the singleplayer, so I'm not sure if I understand the purpose of these buttons correctly.
![image](https://user-images.githubusercontent.com/43277609/116780176-2a299680-aa7b-11eb-9afb-754123157042.png)

**Comment by DarkKronicle** [comment]
That shows tabs. The top one shows the current tab and clicking on it will cycle through your predefined ones. The one on the side is to show you which ones you have. A rewrite of Chat Screen will be done next update.

**Comment by K0-RR** [comment]
Ah ok, so the "Mai" one is misspelled/cropped, right?

**Comment by DarkKronicle** [comment]
Yeah it's cropped. Join the discord if you want to try out the new version early.
