### ISSUE TITLE
[FEATURE] Formatting codes preview

### ISSUE THREAD

**Issue by Xaver106** [DarkKronicle/AdvancedChat#74]
**Is your feature request related to a problem? Please describe.**
If typing with formatting codes, you have to guess how it is going to look. And sometimes you hit the wrong key, but you only realise it when the message appears in chat.

**Describe the solution you'd like**
Format the text in the chat bar, so you can see how it will look befor sending it. The formatted text could be displayed above the text box or you could formatt it right inside the text box.

**Comment by DarkKronicle** [comment]
I'll plan on adding this soon.  The only problem that may occur is when using bold/italic, but if they cause an error I'll just disable them.

**Comment by Xaver106** [comment]
Already fixed with Version 3.3.0 (available on his discord)
Thanks for the quick implementation
