### ISSUE TITLE
[BUG] Filter backgrounds don't work if message processor settings are changed

### ISSUE THREAD

**Issue by GrandpaScout** [DarkKronicle/AdvancedChat#75]
**Describe the bug**
Filter background colors do not work if any of the filter's message processor settings are changed.

**Minecraft Info**
Minecraft information:
- Minecraft Fabric 0.11.3-1.16.5
- Fabric API 0.34.2
- Malilib 0.10.0-dev.21+arne.5
- AdvancedChat 3.2.0-1.16.5

**To Reproduce**
1. Create a new filter
2. Enable and select a background color
3. Enable the action bar or sound processor
4. Trigger the filter
5. The background does not change

**Expected behavior**
I expected to be able to have a message appear in the action bar or have a sound play while also changing the background color of the message.

**Screenshots**
The filter used:
![image](https://user-images.githubusercontent.com/35317603/118458993-48bd9d80-b6c9-11eb-8549-dd851ec99ea8.png)
The expected result (with no processor settings changed):
![image](https://user-images.githubusercontent.com/35317603/118460205-7820da00-b6ca-11eb-8f5d-9fdabb64a983.png)
The actual result (with action bar processor changed):
![image](https://user-images.githubusercontent.com/35317603/118460688-ef566e00-b6ca-11eb-81ed-c8eca848a7da.png)

**Additional context**
This causes the message to completely deny background color changes, even putting the color changes in a different filter or using a filter that searches for something completely different will still make the filter with the processor change stop the background color change.

**Comment by tinyoverflow** [comment]
I can confirm this. When enabling any other processor besides the Chat processor, the background color doesn't work anymore. Furthermore: When disabling the sound (for example) again, the background color only starts working again by turning the rule itself off and on after switching the sound off.

**Comment by DarkKronicle** [comment]
Found the issue. Background color was applied at the last step. This will be available in the AC Split.
