### ISSUE TITLE
chat box slider[FEATURE]

### ISSUE THREAD

**Issue by roxandtol** [DarkKronicle/AdvancedChat#77]
**Is your feature request related to a problem? Please describe.**
No it isn't, it's a quality of life improvement

**Describe the solution you'd like**
A separate slider for the chat box, so you can have a different background on the chat box
**Additional context**
I'm requesting since in vanilla you can have the chatbox to have opacity and the chat itself not

**Comment by DarkKronicle** [comment]
I'll try to add this soon. Thanks for following the template!

**Comment by DarkKronicle** [comment]
https://github.com/DarkKronicle/AdvancedChatCore/wiki/Modules-List Archiving for modules. This is implemented now.
