### ISSUE TITLE
[BUG] Compact mode doesn't work

### ISSUE THREAD

**Issue by bbfh-dev** [DarkKronicle/AdvancedChat#78]
When switching "Background Line Style" to "Compact" chat background doesn't change to compact, what'd be very useful for me

**Minecraft Info**
Minecraft information:
- AdvancedChat version 3.2.0-1.16.5
- Minecraft 1.16.4 FabricMC
- Mods installed: [don't affect if delete all other (except required ones)]

**Expected behavior**
Chat background should fit like in optifine

**Screenshots**
![2021-06-11_14 48 41](https://user-images.githubusercontent.com/61023676/121683062-885b8780-cac5-11eb-989e-bd1f84d37a2e.png)
![2021-06-11_14 48 55](https://user-images.githubusercontent.com/61023676/121683067-8a254b00-cac5-11eb-86d4-a0424ffdd63a.png)

**Comment by DarkKronicle** [comment]
Fixed in the new beta
