### ISSUE TITLE
Tab-completing coordinates is janky

### ISSUE THREAD

**Issue by Boobies** [DarkKronicle/AdvancedChat#79]
This can be seen for the second pair of coordinates with the `fill` command. The options are sorted in the wrong order. Pressing tab multiple times you will get the following, in order:

/fill x1 y1 z1 x2 y2
/fill x1 y1 z1 x2
/fill x1 y1 z1 x2 y2 z2

**Comment by IJustWantANamePlease** [comment]
Well in 1.17 versons they've added an option to stop AdvancedChat from changing order of command suggestions. idk if this option is present in 1.16 versions tough (maybe isn't cuz I couldn't find)

**Comment by DarkKronicle** [comment]
It's just 1.17 now

**Comment by DarkKronicle** [comment]
Archiving for modules https://github.com/DarkKronicle/AdvancedChatCore/wiki/Modules-List
