### ISSUE TITLE
Respect or duplicate vanilla settings

### ISSUE THREAD

**Issue by Madis0** [DarkKronicle/AdvancedChat#8]
I was quite disappointed to see the text being bigger and width smaller than what I had set in vanilla...
I suggest either respecting the vanilla settings or duplicating them to just have the same kind of settings in this mod.

**Comment by DarkKronicle** [comment]
I will try to add this feature next release. Thanks for the request :)

**Comment by DarkKronicle** [comment]
Added! Look out for AdvancedChat-2.0.4 with this!
