### ISSUE TITLE
[BUG] Compact backgrouud

### ISSUE THREAD

**Issue by andreasdc** [DarkKronicle/AdvancedChat#83]
Compact background not working

**Comment by DarkKronicle** [comment]
How so?

**Comment by andreasdc** [comment]
@DarkKronicle it should match text right? It shows normal box background

**Comment by DarkKronicle** [comment]
So it behaves like it isn't set to compact?

**Comment by DarkKronicle** [comment]
Oh this is like #78  I'll look into it

**Comment by DarkKronicle** [comment]
Fixed in new beta
