### ISSUE TITLE
1.17 looses previous config settings[BUG]

### ISSUE THREAD

**Issue by schilzy** [DarkKronicle/AdvancedChat#85]
**Describe the bug**
When I updated to the 1.17 version none of my configs from the 1.16.5 version stayed. I can find the .json file with the old configs in them but it doesn't load them in. 

**Minecraft Info**
Minecraft information:
- AdvancedChat version 1.17
-Also present is the last 1.16.5 version

**Comment by DarkKronicle** [comment]
Archived for modules https://github.com/DarkKronicle/AdvancedChatCore/wiki/Modules-List
