### ISSUE TITLE
[BUG] Child Filters cannot replace background color

### ISSUE THREAD

**Issue by Chronos22Gamer** [DarkKronicle/AdvancedChat#86]
**Describe the bug**
Child filters are unable to replace background colors

**Minecraft Info**
Minecraft information:
- AdvancedChat version: v3.3.0-1.16.5 

**To Reproduce**
1. Import the attached filter
2. Say "Cool" 
3. Hear a "ding" sound (indicating that the filter matched)
4. See no background color replacement

**Expected behavior**
When a message containing "cool" is received, both a "ding" sound should play, and the background color should be replaced

[filter.txt](https://github.com/DarkKronicle/AdvancedChat/files/6779414/filter.txt)

**Comment by StarsDown64** [comment]
May be dupe/related to #71

**Comment by DarkKronicle** [comment]
Fixed in ACFilters
