### ISSUE TITLE
[BUG]Chat Window rendering issue

### ISSUE THREAD

**Issue by schilzy** [DarkKronicle/AdvancedChat#87]
**Describe the bug**
It seems like the chat window is rendering over the top of the text when the chat window is opened. When the text reaches outside the box it goes to White (the colour its meant to be) but when inside the chat box it is grey, as if the translucent black box that is the chat window is sitting on top rather than behind.

**Minecraft Info**
Minecraft information:
- AdvancedChat version- AdvancedChat-3.3.1-1.17-beta2.jar

*Expected behavior**
In previous versions, the chatbox would not affect the colour of the chat text. Also, the Close X and other buttons at the top of the chat box were sitting in the correct place.

**Screenshots**
![image](https://user-images.githubusercontent.com/21233221/125156952-87447580-e1ab-11eb-85f3-b1a8fa6050cc.png)
![image](https://user-images.githubusercontent.com/21233221/125156960-8f9cb080-e1ab-11eb-92f2-cbe21c4dc451.png)

If you need more screenshots or anything please let me know :)

**Comment by schilzy** [comment]
**update on this one.**

 I did a fresh install and it worked perfectly. I had a bit more of a play around in the advancedchat.json file and it seems as tho the 1.17 version does not like the 1.16.5 advancedchat.json file that my configs were in. I just copied them across and it is now visually behaving as it should. 
If you want a copy of my 1.16.5 json files to have a look at let me know, but it is all working and happy now, except that I had to look under the hood as it were to make it behave.

**Comment by schilzy** [comment]
Apologies for the constant updates on this one. 
I have found what the issue is. It's the Chat scale function. If I have it at 100% it's totally fine and happy. Anything under that it breaks and does what the screenshots show.
Hope that helps in finding where the issue hides :)

**Comment by DarkKronicle** [comment]
Finally fixed it in the split 🎉
