### ISSUE TITLE
[BUG]Sound notifications are gone

### ISSUE THREAD

**Issue by schilzy** [DarkKronicle/AdvancedChat#88]
**Describe the bug**
In the 1.17 beta 2 version, the option to add sound notifications to filters is no longer there. 

**Minecraft Info**
Minecraft information:
- AdvancedChat version [AdvancedChat-3.3.1-1.17-beta2.jar]

**Expected behavior**
in previous versions, there was an option to add in a sound notification for chat filters that is now gone.

**Comment by DarkKronicle** [comment]
Will work in the new beta
