### ISSUE TITLE
Detect potential tabs

### ISSUE THREAD

**Issue by Madis0** [DarkKronicle/AdvancedChat#9]
[TabbyChat](https://github.com/killjoy1221/TabbyChat-2) had a nice feature that was able to detect different kinds of tabs depending on chat syntax. For example, a built-in support for [HelpOp] and private messages would be nice. Make it optional though, preferably per-server (e.g in some servers player may only want custom tabs but in others automatic tabs).

**Comment by DarkKronicle** [comment]
Oh yeah, I could see this being nice. I don't know if I would be able to detect chat tabs easily, but I'm pretty sure I am able to do per server.

**Comment by DarkKronicle** [comment]
Archiving for modules https://github.com/DarkKronicle/AdvancedChatCore/wiki/Modules-List
