### ISSUE TITLE
[BUG] Memory Leak

### ISSUE THREAD

**Issue by chaperiez** [DarkKronicle/AdvancedChat#91]
**Describe the bug**
Advanced Chat rendering can account for up to 93% of memory usage if game is run for 2+ hours

**Minecraft Info**
Minecraft information:
- AdvancedChat version [e.g. AdvancedChat-2.0.0-beta]

**To Reproduce**
1. Start Minecraft.
2. Play Minecraft for around 2 hours.
3. Let Advanced Chat destroy your cpu and allocated ram.

**Screenshots**
![Gm1jDglmqu](https://user-images.githubusercontent.com/87503920/126425201-02bd52e6-069e-49e3-8006-82367abe9a67.png)

**Additional context**
Tested on both the latest 1.17 build and the latest stable release on CurseForge

**Comment by DarkKronicle** [comment]
Hmm interesting. Probably some loop while rendering. What's your line storage set to?

**Comment by DarkKronicle** [comment]
I think I found the issue and it should be fixed in the split.
