### ISSUE TITLE
[BUG] Messages get refreshed on rejoin

### ISSUE THREAD

**Issue by roxandtol** [DarkKronicle/AdvancedChat#95]
**Describe the bug**
if you have *Clear on disconnect* off and enter another server, you can see all the messages from before at the same time

**Minecraft Info**
Minecraft information: 1.17.1
- AdvancedChat version: AdvancedChat-3.3.1-beta5

**To Reproduce**
1. Go into a world / server
2. Chat a bit
3. Leave the server
4. Log on into another server
5. You'll see all the messages from before at the same time + the ones you may have when you log on

**Expected behavior**
To not see any messages pop up / only the ones of when you log into a server

**Screenshots**
![](https://i.imgur.com/xuREcuo.png)
![](https://i.imgur.com/4pSVBtV.png)

**Additional context**
- Screenshots taken shortly after logging into those servers
- Chat not focused
- Mod list:
![](https://i.imgur.com/Fs1AaWl.png)

**Comment by DarkKronicle** [comment]
Ok thanks for the report! I'll look into this on the split.

**Comment by DarkKronicle** [comment]
Is fixed in the split
